server:
  port: 8083
  servlet:
    context-path: /bank-service


spring:
  application:
    name: amir-bank-service-mock
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5436}/${DB_NAME:bank_mock}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:0000}
    driver-class-name: org.postgresql.Driver
