version: '1.0'

services:

  postgres:
    image: postgres:11.13
    container_name: payment-service
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=pizza_payment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000