version: '1.0'

services:

  postgres:
    image: postgres:11.13
    container_name: delivery-service
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=pizza_delivery
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000